### PR TITLE
Rename component class name 'container'

### PR DESCRIPTION
**Pull request by fernandoagarcia**
Renamed container so not to clash with other broad container class names

### CODE REVIEW

**Comment by kielabokkie** [comment]
Hi @DonNicoJs, is it possible to release a new minor version that includes this change? Including this component in my project currently messes up the layout.

**Comment by DonNicoJs** [comment]
@kielabokkie I will release a minor this week :) thanks for the ping

**Comment by kielabokkie** [comment]
@DonNicoJs Nice one, cheers!

By the way, the issue was caused because the scoping of the css was correct. It currently says `<style scope>` instead of `<style scoped>`. Renaming the class to be more specific works too though 😄

**Comment by nmezzopera** [comment]
@kielabokkie Released!

**Comment by kielabokkie** [comment]
@DonNicoJs Thanks 😄

**Pull request merged**
